# Create environment:
# $ conda env create --force
name: good
channels:
  - conda-forge
dependencies:
  - python==3.6
  - jupyter==1.0.0
  - numpy==1.13.1
  - pandas==0.20.3
  - requests
  - scikit-learn==0.19.0
  - scipy==0.19.1
  - seaborn
  - statsmodels==0.8.0
  - pip:
    - graphviz
    - git+https://github.com/stroxler/batch_nbconvert
    