# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: continuumio/anaconda3:latest
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "environment.yml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: set up environment
          command: |
            apt-get install -y graphviz
            bash setup.sh --no-start
      # ### Commenting this out for the moment, since we may not need it ###
      # - run:
      #     name: set up jupyter kernel
      #     command: |
      #       source activate good
      #       python -m ipykernel install --name python3 --user
      - run:
          name: build notebooks
          command: |
            source activate good
            batch_nbconvert exec-copy ~/repo ~/built --parallel 2  --cell-timeout 600
      - store_artifacts:
          path: ~/built
          destination: built
